# Generated by Django 2.2.8 on 2019-12-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='authority',
            field=models.CharField(max_length=100),
        ),
    ]
