# Generated by Django 2.2.8 on 2019-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
