# Generated by Django 3.0.1 on 2019-12-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_discuss_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='info',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
