# Generated by Django 3.0.1 on 2019-12-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20191224_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subsection',
        ),
    ]
