# Generated by Django 3.0.1 on 2019-12-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
