# Generated by Django 2.2.8 on 2019-12-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_group_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
