# Generated by Django 2.2.8 on 2019-12-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='ver_number',
            field=models.CharField(max_length=100),
        ),
    ]
