# Generated by Django 3.0.2 on 2020-05-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='number',
            new_name='batch_number',
        ),
        migrations.AddField(
            model_name='student',
            name='ref_photo_url',
            field=models.CharField(default=3170105616, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmembership',
            name='class_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
