# Generated by Django 3.0.2 on 2020-05-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_studentmembership_class_number'),
        ('db', '0014_auto_20200516_2032'),
    ]

    operations = [
    ]
