# Generated by Django 3.0.2 on 2020-05-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_merge_20200518_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmembership',
            old_name='class_number',
            new_name='class_rank',
        ),
    ]
