# Generated by Django 3.0.2 on 2020-05-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20200518_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmembership',
            name='class_number',
        ),
    ]
