# Generated by Django 3.0.2 on 2020-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_remove_studentmembership_class_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
